/*
 * CountriesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.clicksend.rest;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "https://rest.clicksend.com/v3";

}
