/*
 * CountriesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.clicksend.rest;

import com.clicksend.rest.controllers.*;
import com.clicksend.rest.http.client.HttpClient;

public class CountriesAPIClient {
    /**
     * Singleton access to Countries controller
     * @return	Returns the CountriesController instance 
     */
    public CountriesController getCountries() {
        return CountriesController.getInstance();
    }

    /**
     * Get the shared http client currently being used for API calls
     * @return The http client instance currently being used
     */
    public HttpClient getSharedHttpClient() {
        return BaseController.getClientInstance();
    }
    
    /**
     * Set a shared http client to be used for API calls
     * @param httpClient The http client to use
     */
    public void setSharedHttpClient(HttpClient httpClient) {
        BaseController.setClientInstance(httpClient);
    }

    /**
     * Default constructor 
     */     
    public CountriesAPIClient() {
    }

}