/*
 * CountriesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.clicksend.rest.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CountryResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 3518301494250021594L;
    private int httpCode;
    private String responseCode;
    private String responseMsg;
    private List<CountryInfo> data;
    /** GETTER
     * HTTP status code
     */
    @JsonGetter("http_code")
    public int getHttpCode ( ) { 
        return this.httpCode;
    }
    
    /** SETTER
     * HTTP status code
     */
    @JsonSetter("http_code")
    public void setHttpCode (int value) { 
        this.httpCode = value;
    }
 
    /** GETTER
     * Response code of API
     */
    @JsonGetter("response_code")
    public String getResponseCode ( ) { 
        return this.responseCode;
    }
    
    /** SETTER
     * Response code of API
     */
    @JsonSetter("response_code")
    public void setResponseCode (String value) { 
        this.responseCode = value;
    }
 
    /** GETTER
     * Response message of API
     */
    @JsonGetter("response_msg")
    public String getResponseMsg ( ) { 
        return this.responseMsg;
    }
    
    /** SETTER
     * Response message of API
     */
    @JsonSetter("response_msg")
    public void setResponseMsg (String value) { 
        this.responseMsg = value;
    }
 
    /** GETTER
     * This is the list of countries object
     */
    @JsonGetter("data")
    public List<CountryInfo> getData ( ) { 
        return this.data;
    }
    
    /** SETTER
     * This is the list of countries object
     */
    @JsonSetter("data")
    public void setData (List<CountryInfo> value) { 
        this.data = value;
    }
 
}
