/*
 * CountriesAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.clicksend.rest.controllers;

import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import com.fasterxml.jackson.core.type.TypeReference;

import com.clicksend.rest.*;
import com.clicksend.rest.models.*;
import com.clicksend.rest.exceptions.*;
import com.clicksend.rest.http.client.HttpClient;
import com.clicksend.rest.http.client.HttpContext;
import com.clicksend.rest.http.request.HttpRequest;
import com.clicksend.rest.http.response.HttpResponse;
import com.clicksend.rest.http.response.HttpStringResponse;
import com.clicksend.rest.http.client.APICallBack;
import com.clicksend.rest.controllers.syncwrapper.APICallBackCatcher;

public class CountriesController extends BaseController {
    //private static variables for the singleton pattern
    private static final Object syncObject = new Object();
    private static CountriesController instance = null;

    /**
     * Singleton pattern implementation 
     * @return The singleton instance of the CountriesController class 
     */
    public static CountriesController getInstance() {
        if (null == instance) {
            synchronized (syncObject) {
                if (null == instance) {
                    instance = new CountriesController();
                }
            }
        }
        return instance;
    }

    /**
     * This endpoint let user to access countries code and name.
     * @return    Returns the CountryResponse response from the API call 
     */
    public CountryResponse getCountries(
    ) throws Throwable {

        HttpRequest _request = _buildGetCountriesRequest();
        HttpResponse _response = getClientInstance().executeAsString(_request);
        HttpContext _context = new HttpContext(_request, _response);

        return _handleGetCountriesResponse(_context);
    }

    /**
     * This endpoint let user to access countries code and name.
     */
    public void getCountriesAsync(
                final APICallBack<CountryResponse> callBack
    ) {
        Runnable _responseTask = new Runnable() {
            public void run() {

                HttpRequest _request;
                try {
                    _request = _buildGetCountriesRequest();
                } catch (Exception e) {
                    callBack.onFailure(null, e);
                    return;
                }

                // Invoke request and get response
                getClientInstance().executeAsStringAsync(_request, new APICallBack<HttpResponse>() {
                    public void onSuccess(HttpContext _context, HttpResponse _response) {
                        try {
                            CountryResponse returnValue = _handleGetCountriesResponse(_context);
                            callBack.onSuccess(_context, returnValue);
                        } catch (Exception e) {
                            callBack.onFailure(_context, e);
                        }
                    }

                    public void onFailure(HttpContext _context, Throwable _exception) {
                        // Let the caller know of the failure
                        callBack.onFailure(_context, _exception);
                    }
                });
            }
        };

        // Execute async using thread pool
        APIHelper.getScheduler().execute(_responseTask);
    }

    /**
     * Builds the HttpRequest object for getCountries
     */
    private HttpRequest _buildGetCountriesRequest() throws IOException, APIException {
        //the base uri for api requests
        String _baseUri = Configuration.baseUri;

        //prepare query string for API call
        StringBuilder _queryBuilder = new StringBuilder(_baseUri + "/countries");
        //validate and preprocess url
        String _queryUrl = APIHelper.cleanUrl(_queryBuilder);

        //load all headers for the outgoing API request
        Map<String, String> _headers = new HashMap<String, String>();
        _headers.put("user-agent", BaseController.userAgent);
        _headers.put("accept", "application/json");


        //prepare and invoke the API call request to fetch the response
        HttpRequest _request = getClientInstance().get(_queryUrl, _headers, null);

        // Invoke the callback before request if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnBeforeRequest(_request);
        }

        return _request;
    }

    /**
     * Processes the response for getCountries
     * @return An object of type CountryResponse
     */
    private CountryResponse _handleGetCountriesResponse(HttpContext _context)
            throws APIException, IOException {
        HttpResponse _response = _context.getResponse();

        //invoke the callback after response if its not null
        if (getHttpCallBack() != null) {
            getHttpCallBack().OnAfterResponse(_context);
        }

        //handle errors defined at the API level
        validateResponse(_response, _context);

        //extract result from the http response
        String _responseBody = ((HttpStringResponse)_response).getBody();
        CountryResponse _result = APIHelper.deserialize(_responseBody,
                                                        new TypeReference<CountryResponse>(){});

        return _result;
    }

}
